import sys
import os
import asyncio
import io
from typing import Optional, List
import json
import re

# Force UTF-8 for standard streams
if sys.stdout.encoding != 'utf-8':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
if sys.stderr.encoding != 'utf-8':
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')

def clean_video_url(url: str) -> str:
    """
    Clean and normalize URLs for better extraction.
    """
    # 处理抖音链接
    if "douyin.com" in url:
        # 处理包含 modal_id 的精选/推荐等页面，直接归一到视频详情页
        modal_match = re.search(r'modal_id=([^&/?]+)', url)
        if modal_match:
            modal_id = modal_match.group(1)
            if modal_id:
                return f"https://www.douyin.com/video/{modal_id}"
        # 如果是短链接 v.douyin.com，保持原样让 yt-dlp 处理重定向
        if "v.douyin.com" in url:
            return url
        # 如果是普通链接，移除多余的查询参数，只保留视频 ID 相关的
        if "/video/" in url:
            video_id_match = re.search(r'video/(\d+)', url)
            if video_id_match:
                return f"https://www.douyin.com/video/{video_id_match.group(1)}"
    return url

import tempfile

import time

def create_cookie_file(cookies_str: str):
    """
    将 Cookie 字符串转换为 yt-dlp 兼容的 Netscape 格式临时文件。
    """
    if not cookies_str:
        return None
    
    try:
        fd, path = tempfile.mkstemp(suffix='.txt', prefix='cookies_')
        with os.fdopen(fd, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by Browser-Use Bridge\n\n")
            
            # 设置一个较长的过期时间 (1年)
            expiry = int(time.time()) + 31536000
            
            # 抖音的 Cookie 往往包含多个域，Netscape 格式对 domain 校验非常严格
            # 强制为 .douyin.com 和 www.douyin.com 写入
            domains = [".douyin.com", "www.douyin.com", ".amemv.com"]
            
            for item in cookies_str.split(';'):
                if '=' in item:
                    parts = item.strip().split('=', 1)
                    if len(parts) == 2:
                        name, value = parts
                        for d in domains:
                            # 格式: domain, initial_dot, path, secure, expiration, name, value
                            # initial_dot: 如果 domain 以 . 开头则为 TRUE
                            dot_flag = "TRUE" if d.startswith(".") else "FALSE"
                            f.write(f"{d}\t{dot_flag}\t/\tFALSE\t{expiry}\t{name}\t{value}\n")
        return path
    except Exception as e:
        print(f"Error creating cookie file: {e}")
        return None

def get_common_ydl_opts(url: str, cookies_str: Optional[str] = None, custom_ua: Optional[str] = None):
    """
    Get common yt-dlp options with improved compatibility.
    """
    # 优先使用浏览器传来的真实 UA
    ua = custom_ua or 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36'
    
    opts = {
        'quiet': True,
        'no_warnings': True,
        'no_color': True,
        'user_agent': ua,
        'nocheckcertificate': True,
        'ignoreerrors': True,
        'extract_flat': False,
    }
    
    # 强制物理文件 Cookie 注入
    cookie_path = create_cookie_file(cookies_str)
    if cookie_path:
        opts['cookiefile'] = cookie_path
        print(f"Using standard Netscape cookie file: {cookie_path}")

    headers = {
        'User-Agent': ua,
        'Accept': '*/*',
        'Accept-Language': 'zh-CN,zh;q=0.9',
    }

    if "douyin.com" in url or "snssdk.com" in url or "amemv.com" in url:
        opts['referer'] = 'https://www.douyin.com/'
        opts['socket_timeout'] = 30
        headers['Referer'] = 'https://www.douyin.com/'
        headers['Range'] = 'bytes=0-'
        
    # 注意：如果使用了 cookiefile，则不应在 headers 中再传 Cookie，避免 yt-dlp 冲突
    opts['http_headers'] = headers
    return opts

# Add current directory to path so browser_use can be imported
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import yt_dlp
from browser_use import Agent
from browser_use.llm.openai.chat import ChatOpenAI
from browser_use.llm.deepseek.chat import ChatDeepSeek
from browser_use.llm.volcengine.chat import ChatVolcengine
from browser_use.browser import BrowserSession as Browser

app = FastAPI()

# Track running agent tasks to allow cancellation
running_agents = {}

class AgentRequest(BaseModel):
    task: str
    api_key: str
    base_url: str
    model: str

@app.post("/agent/stop")
async def stop_agent():
    """
    Stop all currently running agents.
    """
    print("Received stop request. Cancelling all running agents...")
    count = 0
    for task_id, task in list(running_agents.items()):
        if not task.done():
            task.cancel()
            count += 1
    return {"status": "success", "cancelled_count": count}

@app.post("/agent/run")
async def run_agent_endpoint(request: AgentRequest):
    """
    Wrapper to handle task management for the agent.
    """
    task_id = f"agent_{id(request)}_{asyncio.get_event_loop().time()}"
    loop = asyncio.get_running_loop()
    
    # Create the actual work task
    work_task = loop.create_task(do_run_agent(request))
    running_agents[task_id] = work_task
    
    try:
        result = await work_task
        return result
    except asyncio.CancelledError:
        print(f"Agent task {task_id} was cancelled.")
        return {
            "status": "cancelled",
            "result": "任务已被用户手动停止。",
            "is_successful": False
        }
    finally:
        # Clean up
        if task_id in running_agents:
            del running_agents[task_id]

async def do_run_agent(request: AgentRequest):
    """
    Run the browser-use agent with the provided task and LLM configuration.
    Connects to the local WebView2 instance via CDP (port 9222).
    """
    print(f"Received task: {request.task}")
    print(f"Model: {request.model}")
    print(f"Base URL: {request.base_url}")
    try:
        # 1. Initialize LLM
        # Handle cases where base_url might be empty or specific to a provider
        base_url = request.base_url if request.base_url else None
        
        # Determine which LLM provider to use
        if base_url and ("volces.com" in base_url or "volcengine" in base_url):
            llm = ChatVolcengine(
                api_key=request.api_key,
                base_url=base_url,
                model=request.model,
                temperature=0.0,
            )
        elif base_url and "deepseek" in base_url:
            llm = ChatDeepSeek(
                api_key=request.api_key,
                base_url=base_url,
                model=request.model,
                temperature=0.0,
            )
        else:
            llm = ChatOpenAI(
                api_key=request.api_key,
                base_url=base_url,
                model=request.model,
                temperature=0.0, # Agents work best with low temperature
            )

        # 2. Initialize Browser connecting to existing CDP
        browser = Browser(cdp_url="http://localhost:9222")

        # 3. Initialize Agent
        use_thinking = "flash" not in request.model.lower() and "thinking" not in request.model.lower()
        
        agent = Agent(
            task=request.task,
            llm=llm,
            browser=browser,
            directly_open_url=True, # Enable direct navigation to save steps
            use_thinking=use_thinking,
            max_actions_per_step=10, # Allow more actions per step to reduce overhead
        )

        # 4. Run Agent and return result
        history = await agent.run()
        
        # 5. Extract and Format result
        # Try multiple ways to get the final result text
        result_text = history.final_result()

        # If no explicit final_result, check for errors
        errors = history.errors()
        error_msg = ""
        if errors:
            error_msg = "\n".join([str(e) for e in errors if e is not None])
            print(f"Agent Errors: {error_msg}")
        
        # If no explicit final_result, look for extracted content in history
        if not result_text:
            contents = history.extracted_content()
            if contents:
                result_text = contents[-1]
                
        # If still nothing, check last model actions (maybe it just finished)
        if not result_text:
            actions = history.model_actions()
            if actions:
                # Look for a 'done' action or similar that might have text
                for action in reversed(actions):
                    if 'done' in str(action): # Check action as string since it might be a pydantic object
                        try:
                            # Try to get text if it's a dict or object
                            if isinstance(action, dict):
                                result_text = action.get('done', {}).get('text')
                            else:
                                result_text = getattr(action.done, 'text', None)
                        except:
                            pass
                        if result_text: break
        
        if not result_text:
            if error_msg:
                result_text = f"任务执行失败，错误信息: {error_msg}"
            else:
                result_text = "任务已执行完成，但未返回具体文本结果。请检查浏览器页面是否已达到预期状态。"

        base_success = history.is_successful()
        has_errors = bool(errors)
        is_successful = bool(base_success) and not has_errors

        return {
            "status": "success" if is_successful else "failed",
            "result": result_text,
            "steps": len(history.history),
            "is_successful": is_successful,
            "errors": errors
        }
    
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

class VideoDownloadRequest(BaseModel):
    url: str
    save_path: Optional[str] = None
    format_id: Optional[str] = None
    # 新增字段支持直接数据模式
    direct_data: Optional[dict] = None
    # 新增字段支持 Cookie
    cookies: Optional[str] = None
    # 新增字段支持自定义 User-Agent
    user_agent: Optional[str] = None

@app.post("/video/info")
async def get_video_info(request: VideoDownloadRequest):
    """
    Get video info using yt-dlp from the provided URL, 
    or return direct data if provided.
    """
    # Debug print the request
    print(f"DEBUG: Request payload URL: {request.url}")
    
    # 如果提供了直接数据，跳过 yt-dlp 解析
    if request.direct_data:
        print(f"Received direct video data for: {request.direct_data.get('title')}")
        return {
            "status": "success",
            "title": request.direct_data.get('title'),
            "thumbnail": request.direct_data.get('cover'),
            "duration": request.direct_data.get('duration'),
            "formats": [
                {
                    "format_id": "direct",
                    "ext": "mp4",
                    "resolution": "original",
                    "note": "直接抓取的源地址",
                    "url": request.direct_data.get('url') # 内部使用
                }
            ]
        }

    cleaned_url = clean_video_url(request.url)
    print(f"Received video info request for URL: {request.url} -> Cleaned: {cleaned_url}")
    
    cookie_file = None
    try:
        ydl_opts = get_common_ydl_opts(cleaned_url, request.cookies, request.user_agent)
        cookie_file = ydl_opts.get('cookiefile')
        
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            loop = asyncio.get_event_loop()
            try:
                info = await loop.run_in_executor(None, lambda: ydl.extract_info(cleaned_url, download=False))
                if info is None:
                    raise HTTPException(status_code=400, detail="解析失败：yt-dlp 未能获取视频信息。请确保页面已完全加载。")
            except yt_dlp.utils.DownloadError as de:
                # Provide a more user-friendly message for unsupported or invalid URLs
                error_msg = str(de)
                if "Unsupported URL" in error_msg:
                    raise HTTPException(status_code=400, detail="不支持的 URL。请提供具体的视频播放页面地址。")
                
                # 特殊提示抖音更新
                if "douyin.com" in cleaned_url:
                    raise HTTPException(status_code=400, detail=f"抖音视频解析失败，可能是反爬机制导致或链接失效。\n提示：尝试更新 yt-dlp 库或确保已登录网页端。")
                    
                raise HTTPException(status_code=400, detail=f"视频解析失败: {error_msg}")
            
            formats = []
            if 'formats' in info:
                for f in info['formats']:
                    # 只保留有视频和音频的格式，或者至少有视频的
                    if f.get('vcodec') != 'none':
                        formats.append({
                            'format_id': f.get('format_id'),
                            'ext': f.get('ext'),
                            'resolution': f.get('resolution') or f"{f.get('width')}x{f.get('height')}",
                            'filesize': f.get('filesize'),
                            'note': f.get('format_note') or f.get('format'),
                            'vcodec': f.get('vcodec'),
                            'acodec': f.get('acodec'),
                        })
            
            return {
                "status": "success",
                "title": info.get('title'),
                "thumbnail": info.get('thumbnail'),
                "duration": info.get('duration'),
                "formats": formats
            }
    except HTTPException:
        raise
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"服务器内部错误: {str(e)}")
    finally:
        # 清理临时文件
        if cookie_file and os.path.exists(cookie_file):
            try:
                os.remove(cookie_file)
                print(f"Cleaned up temporary cookie file: {cookie_file}")
            except:
                pass

@app.post("/video/download")
async def download_video(request: VideoDownloadRequest):
    """
    Download video using yt-dlp from the provided URL.
    """
    if not request.save_path:
        raise HTTPException(status_code=400, detail="save_path is required for download")
    
    # 如果提供了直接数据且选择了 direct 格式，直接下载 URL
    target_url = request.url
    if request.direct_data and request.format_id == "direct":
        target_url = request.direct_data.get("url")
        print(f"Downloading direct URL: {target_url}")

    cleaned_url = clean_video_url(target_url)
    print(f"Received video download request for URL: {target_url} -> Cleaned: {cleaned_url}, format_id: {request.format_id}")
    
    cookie_file = None
    try:
        # 确保保存路径存在
        if not os.path.exists(request.save_path):
            os.makedirs(request.save_path)

        # 获取通用配置
        ydl_opts = get_common_ydl_opts(cleaned_url, request.cookies, request.user_agent)
        cookie_file = ydl_opts.get('cookiefile')
        
        # 针对直接下载模式的特殊优化
        if request.format_id == "direct":
            # 抖音直接地址通常需要 generic extractor
            ydl_opts['format'] = 'best'
        else:
            ydl_opts['format'] = request.format_id if request.format_id else 'best'
            
        ydl_opts.update({
            'outtmpl': os.path.join(request.save_path, '%(title)s.%(ext)s'),
            # 如果是直接 URL 模式，手动设置标题，因为 yt-dlp 可能无法从流中解析出标题
            'default_search': 'auto',
        })

        # 如果有 direct_data，设置标题
        if request.direct_data:
            title = request.direct_data.get('title', 'video')
            # 过滤非法字符
            safe_title = "".join([c for c in title if c.isalnum() or c in (' ', '.', '_', '-')]).rstrip()
            ydl_opts['outtmpl'] = os.path.join(request.save_path, f'{safe_title}.%(ext)s')

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            loop = asyncio.get_event_loop()
            try:
                await loop.run_in_executor(None, lambda: ydl.download([cleaned_url]))
            except yt_dlp.utils.DownloadError as de:
                raise HTTPException(status_code=400, detail=f"视频下载失败: {str(de)}")
        
        return {"status": "success", "message": "视频下载成功"}

    except HTTPException:
        raise
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"下载过程中发生错误: {str(e)}")
    finally:
        # 清理临时文件
        if cookie_file and os.path.exists(cookie_file):
            try:
                os.remove(cookie_file)
                print(f"Cleaned up temporary cookie file: {cookie_file}")
            except:
                pass

if __name__ == "__main__":
    import uvicorn
    print("Starting Browser-Use Bridge on port 8000...")
    print("Ensure your C# Browser is running with --remote-debugging-port=9222")
    uvicorn.run(app, host="127.0.0.1", port=8000)
